import os

BOT_TOKEN=os.getenv("BOT_TOKEN")
DATABASE_URL=os.getenv("DATABASE_URL")

OPENAI_API_KEY=os.getenv("OPENAI_API_KEY")

STRIPE_SECRET_KEY=os.getenv("STRIPE_SECRET_KEY")
STRIPE_WEBHOOK_SECRET=os.getenv("STRIPE_WEBHOOK_SECRET")

OWNER_ID=int(os.getenv("OWNER_ID","0"))

INTRO_FILE_ID=os.getenv("INTRO_FILE_ID")
FIRST_MESSAGE_FILE_ID=os.getenv("FIRST_MESSAGE_FILE_ID")

PARISH_LOUNGE=os.getenv("PARISH_LOUNGE")
RADIO_CHANNEL=os.getenv("RADIO_CHANNEL")
